Add 1D kernels for sizes < 1024
ROCmSoftwarePlatform/rocFFT pull request #501
Opened 2024-08-13 22:57 UTC by af-ayala

2024-08-13 23:12 UTC, evetsso approved these changes

2024-08-13 23:22 UTC, eng-flavio-teixeira approved these changes

2024-08-20 18:06 UTC, Kevonosdiaz approved these changes

2024-08-20 19:24 UTC, malcolmroberts commented
Steve mentioned that there are adhoc tests in develop covering this case.  I just `rocfft-test --gtest_filter=adhoc* --test_prob 1` on develop and everything passed.  So I don't understand how this is being tested.

2024-08-21 04:50 UTC, malcolmroberts requested changes
This needs code coverage in our test suite.

2024-08-22 16:28 UTC, malcolmroberts approved these changes

2024-08-22 18:28 UTC, evetsso approved these changes

2024-08-23 19:04 UTC, merged